version: "3"
services:
  mysql:
    image: mysql:8
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
    env_file:
      - env/.dbenv
  api:
    build: 
      context: .
    command: 
      - --debug
      - api
    ports:
      - 8000:8000
    env_file:
      - env/.dbenv
    healthcheck:
      test: "/app/currency-alerter api --health"
      interval: 15s
      timeout: 10s
      retries: 3
  worker:
    build: 
      context: .
    command: 
      - --debug
      - worker
      - --nbp-fetch-interval=30
    env_file:
      - env/.dbenv
      - env/.mailer

  front:
    build:
      context: ./currency-frontend
    ports:
    - "80:80"

volumes:
  db: 